/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/hero-asset.glb --transform --simplify 
Files: ./public/hero-asset.glb [537.96KB] > /Users/unnamddd_admin/Dev/website/hero-asset-transformed.glb [104.16KB] (81%)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/hero-asset-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <spotLight intensity={54.351} angle={Math.PI / 8} penumbra={0.15} decay={2} position={[0, 11.847, -3.576]} rotation={[-1.773, 0, 0]} target={nodes.Spot.target}>
        <primitive object={nodes.Spot.target} position={[0, 0, -1]} />
      </spotLight>
      <mesh geometry={nodes.glow_1.geometry} material={nodes.glow_1.material} position={[-0.101, 0.095, -0.744]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
      <mesh geometry={nodes.surface_2.geometry} material={materials['Material.001']} position={[1.29, -1.127, 0.219]} rotation={[0.37, 1.25, 1.067]} scale={0.687} />
      <mesh geometry={nodes.surface_2001.geometry} material={materials['Material.003']} position={[-1.016, -1.223, 0.124]} rotation={[1.557, 0.056, -0.128]} />
    </group>
  )
}

useGLTF.preload('/hero-asset-transformed.glb')
